// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface AudioConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AudioConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.AudioConfig.AudioEncoding aue = 1;</code>
   * @return The enum numeric value on the wire for aue.
   */
  int getAueValue();
  /**
   * <code>.AudioConfig.AudioEncoding aue = 1;</code>
   * @return The aue.
   */
  AudioConfig.AudioEncoding getAue();

  /**
   * <pre>
   * 采样率（范围为8000-48000）
   * </pre>
   *
   * <code>int32 sampleRate = 2;</code>
   * @return The sampleRate.
   */
  int getSampleRate();
}
