// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

/**
 * <pre>
 * 识别相关设置
 * </pre>
 *
 * Protobuf type {@code SpeechConfig}
 */
public final class SpeechConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SpeechConfig)
    SpeechConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechConfig.newBuilder() to construct.
  private SpeechConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechConfig() {
    lang_ = 0;
    scene_ = 0;
    customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    useCustomWordsId_ = emptyIntList();
    recognizeType_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpeechConfig();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeechConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            lang_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            scene_ = rawValue;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              customWord_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            customWord_.add(s);
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              useCustomWordsId_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            useCustomWordsId_.addInt(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              useCustomWordsId_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              useCustomWordsId_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            recognizeType_ = rawValue;
            break;
          }
          case 48: {

            disableConvertNumber_ = input.readBool();
            break;
          }
          case 56: {

            disablePunctuation_ = input.readBool();
            break;
          }
          case 66: {
            WordsReplace.Builder subBuilder = null;
            if (wordsReplace_ != null) {
              subBuilder = wordsReplace_.toBuilder();
            }
            wordsReplace_ = input.readMessage(WordsReplace.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(wordsReplace_);
              wordsReplace_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        customWord_ = customWord_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        useCustomWordsId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return StreamingProtos.internal_static_SpeechConfig_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StreamingProtos.internal_static_SpeechConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpeechConfig.class, Builder.class);
  }

  /**
   * <pre>
   * 转写的语言
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.Language}
   */
  public enum Language
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <code>MANDARIN = 1;</code>
     */
    MANDARIN(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <code>MANDARIN = 1;</code>
     */
    public static final int MANDARIN_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Language valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Language forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return MANDARIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Language>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Language> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Language>() {
            public Language findValueByNumber(int number) {
              return Language.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SpeechConfig.getDescriptor().getEnumTypes().get(0);
    }

    private static final Language[] VALUES = values();

    public static Language valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Language(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.Language)
  }

  /**
   * <pre>
   * 情景模式，目前仅支持通用0
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.Scene}
   */
  public enum Scene
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GENERALSCENE = 0;</code>
     */
    GENERALSCENE(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GENERALSCENE = 0;</code>
     */
    public static final int GENERALSCENE_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Scene valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Scene forNumber(int value) {
      switch (value) {
        case 0: return GENERALSCENE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Scene>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Scene> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Scene>() {
            public Scene findValueByNumber(int number) {
              return Scene.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SpeechConfig.getDescriptor().getEnumTypes().get(1);
    }

    private static final Scene[] VALUES = values();

    public static Scene valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Scene(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.Scene)
  }

  /**
   * <pre>
   * 识别类型（0-全部，1-仅逐句, 2-仅逐字）
   * </pre>
   *
   * Protobuf enum {@code SpeechConfig.RecognizeType}
   */
  public enum RecognizeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALL = 0;</code>
     */
    ALL(0),
    /**
     * <code>UTTERANCE = 1;</code>
     */
    UTTERANCE(1),
    /**
     * <code>STREAMING = 2;</code>
     */
    STREAMING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ALL = 0;</code>
     */
    public static final int ALL_VALUE = 0;
    /**
     * <code>UTTERANCE = 1;</code>
     */
    public static final int UTTERANCE_VALUE = 1;
    /**
     * <code>STREAMING = 2;</code>
     */
    public static final int STREAMING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RecognizeType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RecognizeType forNumber(int value) {
      switch (value) {
        case 0: return ALL;
        case 1: return UTTERANCE;
        case 2: return STREAMING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RecognizeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RecognizeType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RecognizeType>() {
            public RecognizeType findValueByNumber(int number) {
              return RecognizeType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SpeechConfig.getDescriptor().getEnumTypes().get(2);
    }

    private static final RecognizeType[] VALUES = values();

    public static RecognizeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RecognizeType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SpeechConfig.RecognizeType)
  }

  public static final int LANG_FIELD_NUMBER = 1;
  private int lang_;
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   * @return The enum numeric value on the wire for lang.
   */
  @Override
  public int getLangValue() {
    return lang_;
  }
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   * @return The lang.
   */
  @Override
  public Language getLang() {
    @SuppressWarnings("deprecation")
    Language result = Language.valueOf(lang_);
    return result == null ? Language.UNRECOGNIZED : result;
  }

  public static final int SCENE_FIELD_NUMBER = 2;
  private int scene_;
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   * @return The enum numeric value on the wire for scene.
   */
  @Override
  public int getSceneValue() {
    return scene_;
  }
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   * @return The scene.
   */
  @Override
  public Scene getScene() {
    @SuppressWarnings("deprecation")
    Scene result = Scene.valueOf(scene_);
    return result == null ? Scene.UNRECOGNIZED : result;
  }

  public static final int CUSTOMWORD_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList customWord_;
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @return A list containing the customWord.
   */
  public com.google.protobuf.ProtocolStringList
      getCustomWordList() {
    return customWord_;
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @return The count of customWord.
   */
  public int getCustomWordCount() {
    return customWord_.size();
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @param index The index of the element to return.
   * @return The customWord at the given index.
   */
  public String getCustomWord(int index) {
    return customWord_.get(index);
  }
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the customWord at the given index.
   */
  public com.google.protobuf.ByteString
      getCustomWordBytes(int index) {
    return customWord_.getByteString(index);
  }

  public static final int USECUSTOMWORDSID_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList useCustomWordsId_;
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @return A list containing the useCustomWordsId.
   */
  @Override
  public java.util.List<Integer>
      getUseCustomWordsIdList() {
    return useCustomWordsId_;
  }
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @return The count of useCustomWordsId.
   */
  public int getUseCustomWordsIdCount() {
    return useCustomWordsId_.size();
  }
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @param index The index of the element to return.
   * @return The useCustomWordsId at the given index.
   */
  public int getUseCustomWordsId(int index) {
    return useCustomWordsId_.getInt(index);
  }
  private int useCustomWordsIdMemoizedSerializedSize = -1;

  public static final int RECOGNIZETYPE_FIELD_NUMBER = 5;
  private int recognizeType_;
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   * @return The enum numeric value on the wire for recognizeType.
   */
  @Override
  public int getRecognizeTypeValue() {
    return recognizeType_;
  }
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   * @return The recognizeType.
   */
  @Override
  public RecognizeType getRecognizeType() {
    @SuppressWarnings("deprecation")
    RecognizeType result = RecognizeType.valueOf(recognizeType_);
    return result == null ? RecognizeType.UNRECOGNIZED : result;
  }

  public static final int DISABLECONVERTNUMBER_FIELD_NUMBER = 6;
  private boolean disableConvertNumber_;
  /**
   * <pre>
   * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
   * </pre>
   *
   * <code>bool disableConvertNumber = 6;</code>
   * @return The disableConvertNumber.
   */
  @Override
  public boolean getDisableConvertNumber() {
    return disableConvertNumber_;
  }

  public static final int DISABLEPUNCTUATION_FIELD_NUMBER = 7;
  private boolean disablePunctuation_;
  /**
   * <pre>
   * 加标点。默认false，开启添加标点。true，关闭添加标点。
   * </pre>
   *
   * <code>bool disablePunctuation = 7;</code>
   * @return The disablePunctuation.
   */
  @Override
  public boolean getDisablePunctuation() {
    return disablePunctuation_;
  }

  public static final int WORDSREPLACE_FIELD_NUMBER = 8;
  private WordsReplace wordsReplace_;
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   * @return Whether the wordsReplace field is set.
   */
  @Override
  public boolean hasWordsReplace() {
    return wordsReplace_ != null;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   * @return The wordsReplace.
   */
  @Override
  public WordsReplace getWordsReplace() {
    return wordsReplace_ == null ? WordsReplace.getDefaultInstance() : wordsReplace_;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  @Override
  public WordsReplaceOrBuilder getWordsReplaceOrBuilder() {
    return getWordsReplace();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (lang_ != Language.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, lang_);
    }
    if (scene_ != Scene.GENERALSCENE.getNumber()) {
      output.writeEnum(2, scene_);
    }
    for (int i = 0; i < customWord_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, customWord_.getRaw(i));
    }
    if (getUseCustomWordsIdList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(useCustomWordsIdMemoizedSerializedSize);
    }
    for (int i = 0; i < useCustomWordsId_.size(); i++) {
      output.writeInt32NoTag(useCustomWordsId_.getInt(i));
    }
    if (recognizeType_ != RecognizeType.ALL.getNumber()) {
      output.writeEnum(5, recognizeType_);
    }
    if (disableConvertNumber_ != false) {
      output.writeBool(6, disableConvertNumber_);
    }
    if (disablePunctuation_ != false) {
      output.writeBool(7, disablePunctuation_);
    }
    if (wordsReplace_ != null) {
      output.writeMessage(8, getWordsReplace());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lang_ != Language.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, lang_);
    }
    if (scene_ != Scene.GENERALSCENE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, scene_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < customWord_.size(); i++) {
        dataSize += computeStringSizeNoTag(customWord_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCustomWordList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < useCustomWordsId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(useCustomWordsId_.getInt(i));
      }
      size += dataSize;
      if (!getUseCustomWordsIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      useCustomWordsIdMemoizedSerializedSize = dataSize;
    }
    if (recognizeType_ != RecognizeType.ALL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, recognizeType_);
    }
    if (disableConvertNumber_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, disableConvertNumber_);
    }
    if (disablePunctuation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, disablePunctuation_);
    }
    if (wordsReplace_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getWordsReplace());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpeechConfig)) {
      return super.equals(obj);
    }
    SpeechConfig other = (SpeechConfig) obj;

    if (lang_ != other.lang_) return false;
    if (scene_ != other.scene_) return false;
    if (!getCustomWordList()
        .equals(other.getCustomWordList())) return false;
    if (!getUseCustomWordsIdList()
        .equals(other.getUseCustomWordsIdList())) return false;
    if (recognizeType_ != other.recognizeType_) return false;
    if (getDisableConvertNumber()
        != other.getDisableConvertNumber()) return false;
    if (getDisablePunctuation()
        != other.getDisablePunctuation()) return false;
    if (hasWordsReplace() != other.hasWordsReplace()) return false;
    if (hasWordsReplace()) {
      if (!getWordsReplace()
          .equals(other.getWordsReplace())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LANG_FIELD_NUMBER;
    hash = (53 * hash) + lang_;
    hash = (37 * hash) + SCENE_FIELD_NUMBER;
    hash = (53 * hash) + scene_;
    if (getCustomWordCount() > 0) {
      hash = (37 * hash) + CUSTOMWORD_FIELD_NUMBER;
      hash = (53 * hash) + getCustomWordList().hashCode();
    }
    if (getUseCustomWordsIdCount() > 0) {
      hash = (37 * hash) + USECUSTOMWORDSID_FIELD_NUMBER;
      hash = (53 * hash) + getUseCustomWordsIdList().hashCode();
    }
    hash = (37 * hash) + RECOGNIZETYPE_FIELD_NUMBER;
    hash = (53 * hash) + recognizeType_;
    hash = (37 * hash) + DISABLECONVERTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableConvertNumber());
    hash = (37 * hash) + DISABLEPUNCTUATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisablePunctuation());
    if (hasWordsReplace()) {
      hash = (37 * hash) + WORDSREPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getWordsReplace().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpeechConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpeechConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpeechConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SpeechConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpeechConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpeechConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpeechConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 识别相关设置
   * </pre>
   *
   * Protobuf type {@code SpeechConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SpeechConfig)
      SpeechConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StreamingProtos.internal_static_SpeechConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StreamingProtos.internal_static_SpeechConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpeechConfig.class, Builder.class);
    }

    // Construct using com.yitutech.speech.SpeechConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      lang_ = 0;

      scene_ = 0;

      customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      useCustomWordsId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      recognizeType_ = 0;

      disableConvertNumber_ = false;

      disablePunctuation_ = false;

      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = null;
      } else {
        wordsReplace_ = null;
        wordsReplaceBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return StreamingProtos.internal_static_SpeechConfig_descriptor;
    }

    @Override
    public SpeechConfig getDefaultInstanceForType() {
      return SpeechConfig.getDefaultInstance();
    }

    @Override
    public SpeechConfig build() {
      SpeechConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SpeechConfig buildPartial() {
      SpeechConfig result = new SpeechConfig(this);
      int from_bitField0_ = bitField0_;
      result.lang_ = lang_;
      result.scene_ = scene_;
      if (((bitField0_ & 0x00000001) != 0)) {
        customWord_ = customWord_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.customWord_ = customWord_;
      if (((bitField0_ & 0x00000002) != 0)) {
        useCustomWordsId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.useCustomWordsId_ = useCustomWordsId_;
      result.recognizeType_ = recognizeType_;
      result.disableConvertNumber_ = disableConvertNumber_;
      result.disablePunctuation_ = disablePunctuation_;
      if (wordsReplaceBuilder_ == null) {
        result.wordsReplace_ = wordsReplace_;
      } else {
        result.wordsReplace_ = wordsReplaceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpeechConfig) {
        return mergeFrom((SpeechConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpeechConfig other) {
      if (other == SpeechConfig.getDefaultInstance()) return this;
      if (other.lang_ != 0) {
        setLangValue(other.getLangValue());
      }
      if (other.scene_ != 0) {
        setSceneValue(other.getSceneValue());
      }
      if (!other.customWord_.isEmpty()) {
        if (customWord_.isEmpty()) {
          customWord_ = other.customWord_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCustomWordIsMutable();
          customWord_.addAll(other.customWord_);
        }
        onChanged();
      }
      if (!other.useCustomWordsId_.isEmpty()) {
        if (useCustomWordsId_.isEmpty()) {
          useCustomWordsId_ = other.useCustomWordsId_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureUseCustomWordsIdIsMutable();
          useCustomWordsId_.addAll(other.useCustomWordsId_);
        }
        onChanged();
      }
      if (other.recognizeType_ != 0) {
        setRecognizeTypeValue(other.getRecognizeTypeValue());
      }
      if (other.getDisableConvertNumber() != false) {
        setDisableConvertNumber(other.getDisableConvertNumber());
      }
      if (other.getDisablePunctuation() != false) {
        setDisablePunctuation(other.getDisablePunctuation());
      }
      if (other.hasWordsReplace()) {
        mergeWordsReplace(other.getWordsReplace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpeechConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpeechConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int lang_ = 0;
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     * @return The enum numeric value on the wire for lang.
     */
    @Override
    public int getLangValue() {
      return lang_;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     * @param value The enum numeric value on the wire for lang to set.
     * @return This builder for chaining.
     */
    public Builder setLangValue(int value) {
      
      lang_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     * @return The lang.
     */
    @Override
    public Language getLang() {
      @SuppressWarnings("deprecation")
      Language result = Language.valueOf(lang_);
      return result == null ? Language.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     * @param value The lang to set.
     * @return This builder for chaining.
     */
    public Builder setLang(Language value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      lang_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Language lang = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLang() {
      
      lang_ = 0;
      onChanged();
      return this;
    }

    private int scene_ = 0;
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     * @return The enum numeric value on the wire for scene.
     */
    @Override
    public int getSceneValue() {
      return scene_;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     * @param value The enum numeric value on the wire for scene to set.
     * @return This builder for chaining.
     */
    public Builder setSceneValue(int value) {
      
      scene_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     * @return The scene.
     */
    @Override
    public Scene getScene() {
      @SuppressWarnings("deprecation")
      Scene result = Scene.valueOf(scene_);
      return result == null ? Scene.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     * @param value The scene to set.
     * @return This builder for chaining.
     */
    public Builder setScene(Scene value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      scene_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.Scene scene = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScene() {
      
      scene_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureCustomWordIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        customWord_ = new com.google.protobuf.LazyStringArrayList(customWord_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @return A list containing the customWord.
     */
    public com.google.protobuf.ProtocolStringList
        getCustomWordList() {
      return customWord_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @return The count of customWord.
     */
    public int getCustomWordCount() {
      return customWord_.size();
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param index The index of the element to return.
     * @return The customWord at the given index.
     */
    public String getCustomWord(int index) {
      return customWord_.get(index);
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the customWord at the given index.
     */
    public com.google.protobuf.ByteString
        getCustomWordBytes(int index) {
      return customWord_.getByteString(index);
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param index The index to set the value at.
     * @param value The customWord to set.
     * @return This builder for chaining.
     */
    public Builder setCustomWord(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomWordIsMutable();
      customWord_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param value The customWord to add.
     * @return This builder for chaining.
     */
    public Builder addCustomWord(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureCustomWordIsMutable();
      customWord_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param values The customWord to add.
     * @return This builder for chaining.
     */
    public Builder addAllCustomWord(
        Iterable<String> values) {
      ensureCustomWordIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, customWord_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomWord() {
      customWord_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated string customWord = 3;</code>
     * @param value The bytes of the customWord to add.
     * @return This builder for chaining.
     */
    public Builder addCustomWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureCustomWordIsMutable();
      customWord_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList useCustomWordsId_ = emptyIntList();
    private void ensureUseCustomWordsIdIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        useCustomWordsId_ = mutableCopy(useCustomWordsId_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @return A list containing the useCustomWordsId.
     */
    public java.util.List<Integer>
        getUseCustomWordsIdList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(useCustomWordsId_) : useCustomWordsId_;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @return The count of useCustomWordsId.
     */
    public int getUseCustomWordsIdCount() {
      return useCustomWordsId_.size();
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @param index The index of the element to return.
     * @return The useCustomWordsId at the given index.
     */
    public int getUseCustomWordsId(int index) {
      return useCustomWordsId_.getInt(index);
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @param index The index to set the value at.
     * @param value The useCustomWordsId to set.
     * @return This builder for chaining.
     */
    public Builder setUseCustomWordsId(
        int index, int value) {
      ensureUseCustomWordsIdIsMutable();
      useCustomWordsId_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @param value The useCustomWordsId to add.
     * @return This builder for chaining.
     */
    public Builder addUseCustomWordsId(int value) {
      ensureUseCustomWordsIdIsMutable();
      useCustomWordsId_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @param values The useCustomWordsId to add.
     * @return This builder for chaining.
     */
    public Builder addAllUseCustomWordsId(
        Iterable<? extends Integer> values) {
      ensureUseCustomWordsIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, useCustomWordsId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
     * </pre>
     *
     * <code>repeated int32 useCustomWordsId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUseCustomWordsId() {
      useCustomWordsId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private int recognizeType_ = 0;
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     * @return The enum numeric value on the wire for recognizeType.
     */
    @Override
    public int getRecognizeTypeValue() {
      return recognizeType_;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     * @param value The enum numeric value on the wire for recognizeType to set.
     * @return This builder for chaining.
     */
    public Builder setRecognizeTypeValue(int value) {
      
      recognizeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     * @return The recognizeType.
     */
    @Override
    public RecognizeType getRecognizeType() {
      @SuppressWarnings("deprecation")
      RecognizeType result = RecognizeType.valueOf(recognizeType_);
      return result == null ? RecognizeType.UNRECOGNIZED : result;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     * @param value The recognizeType to set.
     * @return This builder for chaining.
     */
    public Builder setRecognizeType(RecognizeType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      recognizeType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecognizeType() {
      
      recognizeType_ = 0;
      onChanged();
      return this;
    }

    private boolean disableConvertNumber_ ;
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     * @return The disableConvertNumber.
     */
    @Override
    public boolean getDisableConvertNumber() {
      return disableConvertNumber_;
    }
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     * @param value The disableConvertNumber to set.
     * @return This builder for chaining.
     */
    public Builder setDisableConvertNumber(boolean value) {
      
      disableConvertNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
     * </pre>
     *
     * <code>bool disableConvertNumber = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisableConvertNumber() {
      
      disableConvertNumber_ = false;
      onChanged();
      return this;
    }

    private boolean disablePunctuation_ ;
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     * @return The disablePunctuation.
     */
    @Override
    public boolean getDisablePunctuation() {
      return disablePunctuation_;
    }
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     * @param value The disablePunctuation to set.
     * @return This builder for chaining.
     */
    public Builder setDisablePunctuation(boolean value) {
      
      disablePunctuation_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 加标点。默认false，开启添加标点。true，关闭添加标点。
     * </pre>
     *
     * <code>bool disablePunctuation = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisablePunctuation() {
      
      disablePunctuation_ = false;
      onChanged();
      return this;
    }

    private WordsReplace wordsReplace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        WordsReplace, WordsReplace.Builder, WordsReplaceOrBuilder> wordsReplaceBuilder_;
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     * @return Whether the wordsReplace field is set.
     */
    public boolean hasWordsReplace() {
      return wordsReplaceBuilder_ != null || wordsReplace_ != null;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     * @return The wordsReplace.
     */
    public WordsReplace getWordsReplace() {
      if (wordsReplaceBuilder_ == null) {
        return wordsReplace_ == null ? WordsReplace.getDefaultInstance() : wordsReplace_;
      } else {
        return wordsReplaceBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder setWordsReplace(WordsReplace value) {
      if (wordsReplaceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        wordsReplace_ = value;
        onChanged();
      } else {
        wordsReplaceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder setWordsReplace(
        WordsReplace.Builder builderForValue) {
      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = builderForValue.build();
        onChanged();
      } else {
        wordsReplaceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder mergeWordsReplace(WordsReplace value) {
      if (wordsReplaceBuilder_ == null) {
        if (wordsReplace_ != null) {
          wordsReplace_ =
            WordsReplace.newBuilder(wordsReplace_).mergeFrom(value).buildPartial();
        } else {
          wordsReplace_ = value;
        }
        onChanged();
      } else {
        wordsReplaceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public Builder clearWordsReplace() {
      if (wordsReplaceBuilder_ == null) {
        wordsReplace_ = null;
        onChanged();
      } else {
        wordsReplace_ = null;
        wordsReplaceBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public WordsReplace.Builder getWordsReplaceBuilder() {
      
      onChanged();
      return getWordsReplaceFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    public WordsReplaceOrBuilder getWordsReplaceOrBuilder() {
      if (wordsReplaceBuilder_ != null) {
        return wordsReplaceBuilder_.getMessageOrBuilder();
      } else {
        return wordsReplace_ == null ?
            WordsReplace.getDefaultInstance() : wordsReplace_;
      }
    }
    /**
     * <pre>
     * 指定规则替换文本
     * </pre>
     *
     * <code>.WordsReplace wordsReplace = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        WordsReplace, WordsReplace.Builder, WordsReplaceOrBuilder>
        getWordsReplaceFieldBuilder() {
      if (wordsReplaceBuilder_ == null) {
        wordsReplaceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            WordsReplace, WordsReplace.Builder, WordsReplaceOrBuilder>(
                getWordsReplace(),
                getParentForChildren(),
                isClean());
        wordsReplace_ = null;
      }
      return wordsReplaceBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SpeechConfig)
  }

  // @@protoc_insertion_point(class_scope:SpeechConfig)
  private static final SpeechConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpeechConfig();
  }

  public static SpeechConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechConfig>
      PARSER = new com.google.protobuf.AbstractParser<SpeechConfig>() {
    @Override
    public SpeechConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeechConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeechConfig> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpeechConfig> getParserForType() {
    return PARSER;
  }

  @Override
  public SpeechConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

