// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface SpeechConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpeechConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   * @return The enum numeric value on the wire for lang.
   */
  int getLangValue();
  /**
   * <code>.SpeechConfig.Language lang = 1;</code>
   * @return The lang.
   */
  SpeechConfig.Language getLang();

  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   * @return The enum numeric value on the wire for scene.
   */
  int getSceneValue();
  /**
   * <code>.SpeechConfig.Scene scene = 2;</code>
   * @return The scene.
   */
  SpeechConfig.Scene getScene();

  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @return A list containing the customWord.
   */
  java.util.List<String>
      getCustomWordList();
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @return The count of customWord.
   */
  int getCustomWordCount();
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @param index The index of the element to return.
   * @return The customWord at the given index.
   */
  String getCustomWord(int index);
  /**
   * <pre>
   * 自定义词语（支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated string customWord = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the customWord at the given index.
   */
  com.google.protobuf.ByteString
      getCustomWordBytes(int index);

  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @return A list containing the useCustomWordsId.
   */
  java.util.List<Integer> getUseCustomWordsIdList();
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @return The count of useCustomWordsId.
   */
  int getUseCustomWordsIdCount();
  /**
   * <pre>
   * 使用已经上传的自定义词库，填写词库ID。（词语及词库总词数不超过1000个，支持中文2-4个字，中英混合4-8个字符）
   * </pre>
   *
   * <code>repeated int32 useCustomWordsId = 4;</code>
   * @param index The index of the element to return.
   * @return The useCustomWordsId at the given index.
   */
  int getUseCustomWordsId(int index);

  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   * @return The enum numeric value on the wire for recognizeType.
   */
  int getRecognizeTypeValue();
  /**
   * <code>.SpeechConfig.RecognizeType recognizeType = 5;</code>
   * @return The recognizeType.
   */
  SpeechConfig.RecognizeType getRecognizeType();

  /**
   * <pre>
   * 统一数字的转换方式。默认false，开启阿拉伯数字能力。true，关闭阿拉伯数字能力。
   * </pre>
   *
   * <code>bool disableConvertNumber = 6;</code>
   * @return The disableConvertNumber.
   */
  boolean getDisableConvertNumber();

  /**
   * <pre>
   * 加标点。默认false，开启添加标点。true，关闭添加标点。
   * </pre>
   *
   * <code>bool disablePunctuation = 7;</code>
   * @return The disablePunctuation.
   */
  boolean getDisablePunctuation();

  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   * @return Whether the wordsReplace field is set.
   */
  boolean hasWordsReplace();
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   * @return The wordsReplace.
   */
  WordsReplace getWordsReplace();
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * <code>.WordsReplace wordsReplace = 8;</code>
   */
  WordsReplaceOrBuilder getWordsReplaceOrBuilder();
}
