// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface StreamingSpeechConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   * @return Whether the audioConfig field is set.
   */
  boolean hasAudioConfig();
  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   * @return The audioConfig.
   */
  AudioConfig getAudioConfig();
  /**
   * <pre>
   * 音频设置。
   * </pre>
   *
   * <code>.AudioConfig audioConfig = 1;</code>
   */
  AudioConfigOrBuilder getAudioConfigOrBuilder();

  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   * @return Whether the speechConfig field is set.
   */
  boolean hasSpeechConfig();
  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   * @return The speechConfig.
   */
  SpeechConfig getSpeechConfig();
  /**
   * <pre>
   * 识别设置。
   * </pre>
   *
   * <code>.SpeechConfig speechConfig = 2;</code>
   */
  SpeechConfigOrBuilder getSpeechConfigOrBuilder();
}
