// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface StreamingSpeechResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   * @return The globalStreamId.
   */
  String getGlobalStreamId();
  /**
   * <pre>
   * 此次实时处理的全局唯一ID。
   * </pre>
   *
   * <code>string globalStreamId = 1;</code>
   * @return The bytes for globalStreamId.
   */
  com.google.protobuf.ByteString
      getGlobalStreamIdBytes();

  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   * @return The result.
   */
  StreamingSpeechResult getResult();
  /**
   * <pre>
   * 返回识别结果
   * </pre>
   *
   * <code>.StreamingSpeechResult result = 2;</code>
   */
  StreamingSpeechResultOrBuilder getResultOrBuilder();

  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   * @return The status.
   */
  StreamingSpeechStatus getStatus();
  /**
   * <pre>
   * 返回识别状态
   * </pre>
   *
   * <code>.StreamingSpeechStatus status = 3;</code>
   */
  StreamingSpeechStatusOrBuilder getStatusOrBuilder();
}
