// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface StreamingSpeechRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   * @return Whether the streamingSpeechConfig field is set.
   */
  boolean hasStreamingSpeechConfig();
  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   * @return The streamingSpeechConfig.
   */
  StreamingSpeechConfig getStreamingSpeechConfig();
  /**
   * <pre>
   * 音频流设置
   * </pre>
   *
   * <code>.StreamingSpeechConfig streamingSpeechConfig = 1;</code>
   */
  StreamingSpeechConfigOrBuilder getStreamingSpeechConfigOrBuilder();

  /**
   * <pre>
   * 音频数据。每个请求的音频长度最长为60秒。针对实时场景，音频输入的速度超过实时时，性能无法保障，需与依图沟通
   * </pre>
   *
   * <code>bytes audioData = 2;</code>
   * @return The audioData.
   */
  com.google.protobuf.ByteString getAudioData();

  public StreamingSpeechRequest.RequestPayloadCase getRequestPayloadCase();
}
