// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

/**
 * <pre>
 * 音频识别结果
 * </pre>
 *
 * Protobuf type {@code StreamingSpeechResult}
 */
public final class StreamingSpeechResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamingSpeechResult)
        StreamingSpeechResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamingSpeechResult.newBuilder() to construct.
  private StreamingSpeechResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamingSpeechResult() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new StreamingSpeechResult();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamingSpeechResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isFinal_ = input.readBool();
            break;
          }
          case 18: {
            StreamingTranscription.Builder subBuilder = null;
            if (bestTranscription_ != null) {
              subBuilder = bestTranscription_.toBuilder();
            }
            bestTranscription_ = input.readMessage(StreamingTranscription.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bestTranscription_);
              bestTranscription_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return StreamingProtos.internal_static_StreamingSpeechResult_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StreamingProtos.internal_static_StreamingSpeechResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            StreamingSpeechResult.class, Builder.class);
  }

  public static final int ISFINAL_FIELD_NUMBER = 1;
  private boolean isFinal_;
  /**
   * <pre>
   * 此识别结果是否为最终结果
   * </pre>
   *
   * <code>bool isFinal = 1;</code>
   * @return The isFinal.
   */
  @Override
  public boolean getIsFinal() {
    return isFinal_;
  }

  public static final int BESTTRANSCRIPTION_FIELD_NUMBER = 2;
  private StreamingTranscription bestTranscription_;
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   * @return Whether the bestTranscription field is set.
   */
  @Override
  public boolean hasBestTranscription() {
    return bestTranscription_ != null;
  }
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   * @return The bestTranscription.
   */
  @Override
  public StreamingTranscription getBestTranscription() {
    return bestTranscription_ == null ? StreamingTranscription.getDefaultInstance() : bestTranscription_;
  }
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   */
  @Override
  public StreamingTranscriptionOrBuilder getBestTranscriptionOrBuilder() {
    return getBestTranscription();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isFinal_ != false) {
      output.writeBool(1, isFinal_);
    }
    if (bestTranscription_ != null) {
      output.writeMessage(2, getBestTranscription());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isFinal_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isFinal_);
    }
    if (bestTranscription_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBestTranscription());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof StreamingSpeechResult)) {
      return super.equals(obj);
    }
    StreamingSpeechResult other = (StreamingSpeechResult) obj;

    if (getIsFinal()
        != other.getIsFinal()) return false;
    if (hasBestTranscription() != other.hasBestTranscription()) return false;
    if (hasBestTranscription()) {
      if (!getBestTranscription()
          .equals(other.getBestTranscription())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISFINAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFinal());
    if (hasBestTranscription()) {
      hash = (37 * hash) + BESTTRANSCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getBestTranscription().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StreamingSpeechResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamingSpeechResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamingSpeechResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamingSpeechResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamingSpeechResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static StreamingSpeechResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static StreamingSpeechResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamingSpeechResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static StreamingSpeechResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static StreamingSpeechResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static StreamingSpeechResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static StreamingSpeechResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(StreamingSpeechResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 音频识别结果
   * </pre>
   *
   * Protobuf type {@code StreamingSpeechResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamingSpeechResult)
          StreamingSpeechResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StreamingProtos.internal_static_StreamingSpeechResult_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StreamingProtos.internal_static_StreamingSpeechResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StreamingSpeechResult.class, Builder.class);
    }

    // Construct using com.yitutech.speech.StreamingSpeechResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      isFinal_ = false;

      if (bestTranscriptionBuilder_ == null) {
        bestTranscription_ = null;
      } else {
        bestTranscription_ = null;
        bestTranscriptionBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return StreamingProtos.internal_static_StreamingSpeechResult_descriptor;
    }

    @Override
    public StreamingSpeechResult getDefaultInstanceForType() {
      return StreamingSpeechResult.getDefaultInstance();
    }

    @Override
    public StreamingSpeechResult build() {
      StreamingSpeechResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StreamingSpeechResult buildPartial() {
      StreamingSpeechResult result = new StreamingSpeechResult(this);
      result.isFinal_ = isFinal_;
      if (bestTranscriptionBuilder_ == null) {
        result.bestTranscription_ = bestTranscription_;
      } else {
        result.bestTranscription_ = bestTranscriptionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StreamingSpeechResult) {
        return mergeFrom((StreamingSpeechResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StreamingSpeechResult other) {
      if (other == StreamingSpeechResult.getDefaultInstance()) return this;
      if (other.getIsFinal() != false) {
        setIsFinal(other.getIsFinal());
      }
      if (other.hasBestTranscription()) {
        mergeBestTranscription(other.getBestTranscription());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StreamingSpeechResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StreamingSpeechResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isFinal_ ;
    /**
     * <pre>
     * 此识别结果是否为最终结果
     * </pre>
     *
     * <code>bool isFinal = 1;</code>
     * @return The isFinal.
     */
    @Override
    public boolean getIsFinal() {
      return isFinal_;
    }
    /**
     * <pre>
     * 此识别结果是否为最终结果
     * </pre>
     *
     * <code>bool isFinal = 1;</code>
     * @param value The isFinal to set.
     * @return This builder for chaining.
     */
    public Builder setIsFinal(boolean value) {
      
      isFinal_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 此识别结果是否为最终结果
     * </pre>
     *
     * <code>bool isFinal = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsFinal() {
      
      isFinal_ = false;
      onChanged();
      return this;
    }

    private StreamingTranscription bestTranscription_;
    private com.google.protobuf.SingleFieldBuilderV3<
            StreamingTranscription, StreamingTranscription.Builder, StreamingTranscriptionOrBuilder> bestTranscriptionBuilder_;
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     * @return Whether the bestTranscription field is set.
     */
    public boolean hasBestTranscription() {
      return bestTranscriptionBuilder_ != null || bestTranscription_ != null;
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     * @return The bestTranscription.
     */
    public StreamingTranscription getBestTranscription() {
      if (bestTranscriptionBuilder_ == null) {
        return bestTranscription_ == null ? StreamingTranscription.getDefaultInstance() : bestTranscription_;
      } else {
        return bestTranscriptionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public Builder setBestTranscription(StreamingTranscription value) {
      if (bestTranscriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bestTranscription_ = value;
        onChanged();
      } else {
        bestTranscriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public Builder setBestTranscription(
        StreamingTranscription.Builder builderForValue) {
      if (bestTranscriptionBuilder_ == null) {
        bestTranscription_ = builderForValue.build();
        onChanged();
      } else {
        bestTranscriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public Builder mergeBestTranscription(StreamingTranscription value) {
      if (bestTranscriptionBuilder_ == null) {
        if (bestTranscription_ != null) {
          bestTranscription_ =
            StreamingTranscription.newBuilder(bestTranscription_).mergeFrom(value).buildPartial();
        } else {
          bestTranscription_ = value;
        }
        onChanged();
      } else {
        bestTranscriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public Builder clearBestTranscription() {
      if (bestTranscriptionBuilder_ == null) {
        bestTranscription_ = null;
        onChanged();
      } else {
        bestTranscription_ = null;
        bestTranscriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public StreamingTranscription.Builder getBestTranscriptionBuilder() {
      
      onChanged();
      return getBestTranscriptionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    public StreamingTranscriptionOrBuilder getBestTranscriptionOrBuilder() {
      if (bestTranscriptionBuilder_ != null) {
        return bestTranscriptionBuilder_.getMessageOrBuilder();
      } else {
        return bestTranscription_ == null ?
            StreamingTranscription.getDefaultInstance() : bestTranscription_;
      }
    }
    /**
     * <pre>
     * 最好的转写候选
     * </pre>
     *
     * <code>.StreamingTranscription bestTranscription = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            StreamingTranscription, StreamingTranscription.Builder, StreamingTranscriptionOrBuilder>
        getBestTranscriptionFieldBuilder() {
      if (bestTranscriptionBuilder_ == null) {
        bestTranscriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                StreamingTranscription, StreamingTranscription.Builder, StreamingTranscriptionOrBuilder>(
                getBestTranscription(),
                getParentForChildren(),
                isClean());
        bestTranscription_ = null;
      }
      return bestTranscriptionBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamingSpeechResult)
  }

  // @@protoc_insertion_point(class_scope:StreamingSpeechResult)
  private static final StreamingSpeechResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new StreamingSpeechResult();
  }

  public static StreamingSpeechResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamingSpeechResult>
      PARSER = new com.google.protobuf.AbstractParser<StreamingSpeechResult>() {
    @Override
    public StreamingSpeechResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamingSpeechResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamingSpeechResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamingSpeechResult> getParserForType() {
    return PARSER;
  }

  @Override
  public StreamingSpeechResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

