// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface StreamingSpeechResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingSpeechResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 此识别结果是否为最终结果
   * </pre>
   *
   * <code>bool isFinal = 1;</code>
   * @return The isFinal.
   */
  boolean getIsFinal();

  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   * @return Whether the bestTranscription field is set.
   */
  boolean hasBestTranscription();
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   * @return The bestTranscription.
   */
  StreamingTranscription getBestTranscription();
  /**
   * <pre>
   * 最好的转写候选
   * </pre>
   *
   * <code>.StreamingTranscription bestTranscription = 2;</code>
   */
  StreamingTranscriptionOrBuilder getBestTranscriptionOrBuilder();
}
