// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface StreamingTranscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamingTranscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 转写结果
   * </pre>
   *
   * <code>string transcribedText = 1;</code>
   * @return The transcribedText.
   */
  String getTranscribedText();
  /**
   * <pre>
   * 转写结果
   * </pre>
   *
   * <code>string transcribedText = 1;</code>
   * @return The bytes for transcribedText.
   */
  com.google.protobuf.ByteString
      getTranscribedTextBytes();

  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 2;</code>
   */
  java.util.List<StreamingTranscriptionPiece>
      getPieceList();
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 2;</code>
   */
  StreamingTranscriptionPiece getPiece(int index);
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 2;</code>
   */
  int getPieceCount();
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 2;</code>
   */
  java.util.List<? extends StreamingTranscriptionPieceOrBuilder>
      getPieceOrBuilderList();
  /**
   * <pre>
   * 转写结果的分解（只对final状态结果有效，返回每个字及标点的详细信息）
   * </pre>
   *
   * <code>repeated .StreamingTranscriptionPiece piece = 2;</code>
   */
  StreamingTranscriptionPieceOrBuilder getPieceOrBuilder(
          int index);
}
