// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

/**
 * <pre>
 * 指定规则替换文本
 * </pre>
 *
 * Protobuf type {@code WordsReplace}
 */
public final class WordsReplace extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WordsReplace)
    WordsReplaceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WordsReplace.newBuilder() to construct.
  private WordsReplace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WordsReplace() {
    keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new WordsReplace();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WordsReplace(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              keywords_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            keywords_.add(s);
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              replace_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            replace_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        keywords_ = keywords_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        replace_ = replace_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return StreamingProtos.internal_static_WordsReplace_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StreamingProtos.internal_static_WordsReplace_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WordsReplace.class, Builder.class);
  }

  public static final int KEYWORDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList keywords_;
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @return A list containing the keywords.
   */
  public com.google.protobuf.ProtocolStringList
      getKeywordsList() {
    return keywords_;
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @return The count of keywords.
   */
  public int getKeywordsCount() {
    return keywords_.size();
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  public String getKeywords(int index) {
    return keywords_.get(index);
  }
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  public com.google.protobuf.ByteString
      getKeywordsBytes(int index) {
    return keywords_.getByteString(index);
  }

  public static final int REPLACE_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList replace_;
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @return A list containing the replace.
   */
  public com.google.protobuf.ProtocolStringList
      getReplaceList() {
    return replace_;
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @return The count of replace.
   */
  public int getReplaceCount() {
    return replace_.size();
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @param index The index of the element to return.
   * @return The replace at the given index.
   */
  public String getReplace(int index) {
    return replace_.get(index);
  }
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the replace at the given index.
   */
  public com.google.protobuf.ByteString
      getReplaceBytes(int index) {
    return replace_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < keywords_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keywords_.getRaw(i));
    }
    for (int i = 0; i < replace_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, replace_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < keywords_.size(); i++) {
        dataSize += computeStringSizeNoTag(keywords_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeywordsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < replace_.size(); i++) {
        dataSize += computeStringSizeNoTag(replace_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReplaceList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WordsReplace)) {
      return super.equals(obj);
    }
    WordsReplace other = (WordsReplace) obj;

    if (!getKeywordsList()
        .equals(other.getKeywordsList())) return false;
    if (!getReplaceList()
        .equals(other.getReplaceList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKeywordsCount() > 0) {
      hash = (37 * hash) + KEYWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getKeywordsList().hashCode();
    }
    if (getReplaceCount() > 0) {
      hash = (37 * hash) + REPLACE_FIELD_NUMBER;
      hash = (53 * hash) + getReplaceList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WordsReplace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WordsReplace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WordsReplace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WordsReplace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WordsReplace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WordsReplace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WordsReplace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WordsReplace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WordsReplace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WordsReplace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WordsReplace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WordsReplace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WordsReplace prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 指定规则替换文本
   * </pre>
   *
   * Protobuf type {@code WordsReplace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WordsReplace)
      WordsReplaceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StreamingProtos.internal_static_WordsReplace_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StreamingProtos.internal_static_WordsReplace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WordsReplace.class, Builder.class);
    }

    // Construct using com.yitutech.speech.WordsReplace.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return StreamingProtos.internal_static_WordsReplace_descriptor;
    }

    @Override
    public WordsReplace getDefaultInstanceForType() {
      return WordsReplace.getDefaultInstance();
    }

    @Override
    public WordsReplace build() {
      WordsReplace result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public WordsReplace buildPartial() {
      WordsReplace result = new WordsReplace(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        keywords_ = keywords_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keywords_ = keywords_;
      if (((bitField0_ & 0x00000002) != 0)) {
        replace_ = replace_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.replace_ = replace_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WordsReplace) {
        return mergeFrom((WordsReplace)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WordsReplace other) {
      if (other == WordsReplace.getDefaultInstance()) return this;
      if (!other.keywords_.isEmpty()) {
        if (keywords_.isEmpty()) {
          keywords_ = other.keywords_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeywordsIsMutable();
          keywords_.addAll(other.keywords_);
        }
        onChanged();
      }
      if (!other.replace_.isEmpty()) {
        if (replace_.isEmpty()) {
          replace_ = other.replace_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureReplaceIsMutable();
          replace_.addAll(other.replace_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WordsReplace parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WordsReplace) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKeywordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        keywords_ = new com.google.protobuf.LazyStringArrayList(keywords_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @return A list containing the keywords.
     */
    public com.google.protobuf.ProtocolStringList
        getKeywordsList() {
      return keywords_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @return The count of keywords.
     */
    public int getKeywordsCount() {
      return keywords_.size();
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param index The index of the element to return.
     * @return The keywords at the given index.
     */
    public String getKeywords(int index) {
      return keywords_.get(index);
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keywords at the given index.
     */
    public com.google.protobuf.ByteString
        getKeywordsBytes(int index) {
      return keywords_.getByteString(index);
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param index The index to set the value at.
     * @param value The keywords to set.
     * @return This builder for chaining.
     */
    public Builder setKeywords(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
      keywords_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param value The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywords(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeywordsIsMutable();
      keywords_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param values The keywords to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeywords(
        Iterable<String> values) {
      ensureKeywordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keywords_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeywords() {
      keywords_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 待替换的文本。最多支持100个词
     * </pre>
     *
     * <code>repeated string keywords = 1;</code>
     * @param value The bytes of the keywords to add.
     * @return This builder for chaining.
     */
    public Builder addKeywordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKeywordsIsMutable();
      keywords_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureReplaceIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        replace_ = new com.google.protobuf.LazyStringArrayList(replace_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @return A list containing the replace.
     */
    public com.google.protobuf.ProtocolStringList
        getReplaceList() {
      return replace_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @return The count of replace.
     */
    public int getReplaceCount() {
      return replace_.size();
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param index The index of the element to return.
     * @return The replace at the given index.
     */
    public String getReplace(int index) {
      return replace_.get(index);
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the replace at the given index.
     */
    public com.google.protobuf.ByteString
        getReplaceBytes(int index) {
      return replace_.getByteString(index);
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param index The index to set the value at.
     * @param value The replace to set.
     * @return This builder for chaining.
     */
    public Builder setReplace(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceIsMutable();
      replace_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param value The replace to add.
     * @return This builder for chaining.
     */
    public Builder addReplace(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureReplaceIsMutable();
      replace_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param values The replace to add.
     * @return This builder for chaining.
     */
    public Builder addAllReplace(
        Iterable<String> values) {
      ensureReplaceIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, replace_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplace() {
      replace_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
     * </pre>
     *
     * <code>repeated string replace = 2;</code>
     * @param value The bytes of the replace to add.
     * @return This builder for chaining.
     */
    public Builder addReplaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureReplaceIsMutable();
      replace_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WordsReplace)
  }

  // @@protoc_insertion_point(class_scope:WordsReplace)
  private static final WordsReplace DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WordsReplace();
  }

  public static WordsReplace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WordsReplace>
      PARSER = new com.google.protobuf.AbstractParser<WordsReplace>() {
    @Override
    public WordsReplace parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WordsReplace(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WordsReplace> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WordsReplace> getParserForType() {
    return PARSER;
  }

  @Override
  public WordsReplace getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

