// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YituAudioSpeech.proto

package com.yitutech.speech;

public interface WordsReplaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WordsReplace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @return A list containing the keywords.
   */
  java.util.List<String>
      getKeywordsList();
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  String getKeywords(int index);
  /**
   * <pre>
   * 待替换的文本。最多支持100个词
   * </pre>
   *
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @return A list containing the replace.
   */
  java.util.List<String>
      getReplaceList();
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @return The count of replace.
   */
  int getReplaceCount();
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @param index The index of the element to return.
   * @return The replace at the given index.
   */
  String getReplace(int index);
  /**
   * <pre>
   * 替换后的字符。不指定时替换为空。最多支持100个符号，和待替换文本一一对应
   * </pre>
   *
   * <code>repeated string replace = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the replace at the given index.
   */
  com.google.protobuf.ByteString
      getReplaceBytes(int index);
}
